// <auto-generated />
namespace Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addfieldFavoriteforbuyingCar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addfieldFavoriteforbuyingCar));
        
        string IMigrationMetadata.Id
        {
            get { return "201803090930155_add field Favorite for buyingCar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
