// <auto-generated />
namespace Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddfieldNewOfferintoBuingCar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddfieldNewOfferintoBuingCar));
        
        string IMigrationMetadata.Id
        {
            get { return "201803070823250_Add field NewOffer into BuingCar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
